---
- name: install Docker
  hosts: web-server
  become: true
  vars:
    dockerPath: "/root/data"

  tasks:
    - name: Install apt-transport-https
      yum:
        name:
          - apt-transport-https
          - ca-certificates
          - lsb-release
          - gnupg
        state: latest
        update_cache: true

    - name: Add signing key
      yum_key:
        url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
        state: present

    - name: Add repository into sources list
      yum_repository:
        repo: "deb [arch={{ ansible_architecture }}] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
        state: present
        filename: docker

    - name: Install Docker
      yum:
        name:
          - docker
          - docker.io
          - docker-compose
          - docker-registry
        state: latest
        update_cache: true

    # - name: "Installing epel-release packages"
    #   yum:
    #     name: epel-release
    #     state: present

    # - name: "Installing system packages"
    #   yum:
    #     name: ['net-tools', 'telnet', 'vim', 'iptables-services']
    #     state: present

    # - name: Installing Docker Prerequisite packages
    #   yum:
    #     name: ['yum-utils', 'device-mapper-persistent-data', 'lvm2', 'xfsprogs']
    #     state: present

    # - name: Add repository
    #   yum_repository:
    #     name: epel
    #     description: EPEL YUM repo
    #     baseurl: https://download.docker.com/linux/centos/docker-ce.repo

    # - name: "Installing Docker latest"
    #   yum:
    #     name: ['docker-ce', 'docker-ce-cli', 'containerd.io', 'python-docker']
    #     state: present

    # - name: " Starting and Enabling Docker service"
    #   service:
    #     name: docker
    #     state: started
    #     enabled: yes

    # - name: Stop firewalld
    #   service: name=firewalld state=stopped

    # - name: Disable firewalld
    #   service: name=firewalld enabled=no

    # - name: Mask firewalld
    #   service: name=firewalld masked=yes

    # - name: Start iptables service
    #   systemd:
    #     state: started
    #     name: iptables
    #     enabled: yes

    - name: Copy file
      copy:
        src: '{{WORKPLACE_DIR}}/{{item}}'
        dest: "{{dockerPath}}"
      with_items:
        - docker-compose.yml
    
    - name: Log into DockerHub
      docker_login:
        username: '{{DOCKER_USERNAME}}' 
        password: '{{DOCKER_PASSWORD}}'
    
    - name: Start a container
      shell: |
          docker pull {{IMAGE_NAME}}
          docker-compose up -d
      args:
        chdir: '{{dockerPath}}'